### PR TITLE
Fix Windows 8 issue relating to focus and scope.

### PR DESCRIPTION
**Pull request by mcaskill**
The issue being that the `.sod_list_wrapper` does not properly show and the selection is not processed. I'm sure @cah4a can explain this better.

This commit from @cah4a fixes issues under Windows 8 with Internet Explorer and Chrome (and possibly Firefox).

This resolves (based on the conversations) the following issues : #6, #7, #14

### CODE REVIEW

**Comment by cah4a** [comment]
IE unlike other browsers sends focusin event to select (before click event) while click on the dropdown.
So the trick is to check that the target of focusin event is not a dropdown.

**Comment by mcaskill** [comment]
@cah4a I hope you don't mind me making a pull request on your behalf.

**Comment by cah4a** [comment]
@mcaskill Any time)
Do I need to add minified version?

**Comment by vestman** [comment]
Thanks a lot @mcaskill and @cah4a

**Pull request merged**
