### PR TITLE
selectordie.js: fix ipad bug

### PR DESCRIPTION
**Pull request by builtbylane**

### CODE REVIEW

**Comment by vestman** [comment]
Hi,

Is this related to this?
https://github.com/vestman/Select-or-Die/issues/8

Cheers!

**Comment by builtbylane** [comment]
yes. from the sound of it, that's what I was encountering. despite being hidden, the options part is somehow getting 'tapped' on the ipad. it wasn't actually resetting, it was triggering a click on the topmost item. This fixes that issue

**Comment by vestman** [comment]
Thanks, @builtbylane!

**Comment by builtbylane** [comment]
my pleasure

**Pull request merged**
